Repository AppiumTestDistribution/appium-device-farm, pull requests merged in 2023-12, with the labels that each got.

#902 Fix nested interval when updating devices from node.
  .eslintrc.js
  .gitignore
  azure-pipelines.yml
  docs/server-args.md
  package-lock.json
  package.json
  sample-config.json
  src/app.ts
  src/data-service/device-service.ts
  src/device-managers/AndroidDeviceManager.ts
  src/device-managers/IOSDeviceManager.ts
  src/device-managers/NodeDevices.ts
  src/device-managers/cloud/Devices.ts
  src/device-managers/index.ts
  src/device-utils.ts
  src/helpers.ts
  src/interfaces/IDeviceManager.ts
  src/interfaces/IPluginArgs.ts
  src/plugin.ts
  src/wd-command-proxy.ts
  test/e2e/android/cloud/bs.spec.ts
  test/e2e/android/cloud/conf.spec.js
  test/e2e/android/cloud/confIOS.js
  test/e2e/android/cloud/confIOS.ts
  test/e2e/android/cloud/lambdaTest.spec.js
  test/e2e/android/cloud/lambdaTest.spec.ts
  test/e2e/android/cloud/pcloudy.spec.js
  test/e2e/android/cloud/pcloudy.spec.ts
  test/e2e/browserstack.spec.ts
  test/e2e/e2ehelper.ts
  test/e2e/hubnode.spec.ts
  test/e2e/pcloudy.spec.ts
  test/e2e/plugin.spec.js
  test/e2e/plugin.spec.ts
  test/integration/01iOSSimulator.spec.js
  test/integration/02iOSDevices.spec.js
  test/integration/androidDevices.spec.js
  test/unit/AndroidDeviceManager.spec.ts
  test/unit/DeviceModel.spec.js
  test/unit/IOSDeviceManager.spec.js
  test/unit/device-utils.spec.js
  tsconfig.json
  vite.config.ts
  web/package-lock.json
Labels: bump:minor

#915 #914 fix remove device from remote
  package-lock.json
  package.json
  src/device-managers/AndroidDeviceManager.ts
  test/e2e/plugin.spec.ts
  test/integration/01iOSSimulator.spec.js
Labels: bump:patch

#918 fix android remove device from hub
  package-lock.json
  package.json
  src/device-managers/AndroidDeviceManager.ts
Labels: bump:patch

#922 Fix iOS remove devices from hub
  package-lock.json
  package.json
  server-config.json
  src/data-service/device-service.ts
  src/device-managers/AndroidDeviceManager.ts
  src/device-managers/IOSDeviceManager.ts
  src/device-managers/NodeDevices.ts
  src/device-managers/index.ts
  src/device-utils.ts
  src/interfaces/IDeviceManager.ts
  src/interfaces/IPluginArgs.ts
  src/plugin.ts
  src/types/DeviceUpdate.ts
  src/wd-command-proxy.ts
  web/src/components/device-card/device-card/device-card.tsx
Labels: bump:minor

#934 Fix pCloudy url issue
  package-lock.json
  package.json
  src/plugin.ts
Labels: bump:patch

#936 fix pCloudy session and also clean up logs
  package-lock.json
  package.json
  serverConfig/pcloudy-config.json
  src/device-utils.ts
  src/helpers.ts
  src/plugin.ts
  test/e2e/pcloudy.spec.ts
Labels: bump:patch

#929 Pending session should be cleared when failing to create session
  docs/architecture.md
  mkdocs.yml
  package-lock.json
  package.json
  sample-config.json
  src/app.ts
  src/chromeUtils.ts
  src/commands/handle.ts
  src/data-service/db.ts
  src/data-service/device-service.ts
  src/data-service/pending-sessions-service.ts
  src/data-service/pluginArgs.ts
  src/device-managers/AndroidDeviceManager.ts
  src/device-managers/IOSDeviceManager.ts
  src/device-utils.ts
  src/helpers.ts
  src/interfaces/IDeviceFilterOptions.ts
  src/interfaces/IPluginArgs.ts
  src/interfaces/ISessionCapability.ts
  src/logger.ts
  src/plugin.ts
  src/public/static/js/main.f8523680.js.map
  src/wd-command-proxy.ts
  test/e2e/android/cloud/bs.spec.ts
  test/e2e/android/cloud/confIOS.ts
  test/e2e/android/cloud/lambdaTest.spec.ts
  test/e2e/android/cloud/pcloudy.spec.ts
  test/e2e/browserstack.spec.ts
  test/e2e/e2ehelper.ts
  test/e2e/hubnode.spec.ts
  test/e2e/hubnode/forward-request.spec.ts
  test/e2e/hubnode/hubnode.spec.ts
  test/e2e/ios/conf1.spec.js
  test/e2e/pcloudy.spec.ts
  test/e2e/plugin-harness.ts
  test/e2e/plugin.spec.ts
  test/integration/androidDevices.spec.js
  test/integration/androidDevices.spec.ts
  test/integration/ios/01iOSSimulator.spec.ts
  test/integration/ios/02iOSDevices.spec.ts
  test/unit/AndroidDeviceManager.spec.ts
  test/unit/DeviceModel.spec.ts
  test/unit/IOSDeviceManager.spec.js
  test/unit/RemoteIOs.spec.js
  test/unit/config.spec.js
  test/unit/device-service.spec.js
  test/unit/device-service.spec.ts
  test/unit/device-utils.spec.js
  test/unit/device-utils.spec.ts
  test/unit/plugin.spec.ts
  tsconfig.json
  typings/appium-adb/index.d.ts
  typings/appium-support/index.d.ts
  typings/node-simctl/index.d.ts
  web/src/api-service/index.ts
  web/src/components/device-card/device-card/device-card.tsx
  web/yarn.lock
Labels: bump:patch

#942 bump version
  docs/reference/commands/a.md
  package-lock.json
  package.json
  src/app.ts
  web/yarn.lock
Labels: bump:patch

#948 Fix format url for api
  package-lock.json
  web/src/api-service/api-client.ts
  web/yarn.lock
Labels: bug
