Repository AppiumTestDistribution/appium-device-farm, pull requests merged in 2023-04, with the labels that each got.

#703 UI revamp
  package-lock.json
  package.json
  src/public/asset-manifest.json
  src/public/index.html
  src/public/static/css/main.b20c63fe.css
  src/public/static/css/main.b20c63fe.css.map
  src/public/static/css/main.d9eeadcd.css
  src/public/static/css/main.d9eeadcd.css.map
  src/public/static/js/main.4862eae7.js
  src/public/static/js/main.4862eae7.js.LICENSE.txt
  src/public/static/js/main.4862eae7.js.map
  src/public/static/js/main.64b52f6d.js
  src/public/static/js/main.64b52f6d.js.LICENSE.txt
  src/public/static/js/main.64b52f6d.js.map
  src/public/static/media/android-nav-icon.4670118e9f775081ed597e634764f605.svg
  src/public/static/media/apple-icon.5112967f592a1aeff8323b26823c2bd8.svg
  src/public/static/media/apple-icon.a17e460ff848e58ea357b7d5e7dbb21f.svg
  src/public/static/media/apple-nav-icon.429cf1f0405cd5c622edbfb5835e22f8.svg
  src/public/static/media/apple-new-icon.568712db98ff3f83690a4e07bfe3d702.svg
  src/public/static/media/cancel-green-icon.71453b46237edaab5014a92125a3ed69.svg
  src/public/static/media/cancel-red-icon.52d51b858c8e96a30d4f9d79b52b92ea.svg
  src/public/static/media/device-farm-logo.90f2df7d84e57174f9c8.png
  src/public/static/media/link-icon.7336176ff32688423a9800543c6ee9f8.svg
  src/public/static/media/session-icon.de13b0401a71c8b2ee17117134dabd57.svg
  src/public/version.txt
  test/e2e/android/cloud/conf.spec.js
  test/e2e/android/cloud/confIOS.js
  test/e2e/android/conf2.spec.js
  test/e2e/android/conf3.spec.js
  web/src/App.css
  web/src/assets/android-nav-icon.svg
  web/src/assets/apple-icon.svg
  web/src/assets/apple-nav-icon.svg
  web/src/assets/cancel-green-icon.svg
  web/src/assets/cancel-red-icon.svg
  web/src/assets/device-farm-logo.png
  web/src/assets/link-icon.svg
  web/src/assets/session-icon.svg
  web/src/components/device-card/device-card/device-card.css
  web/src/components/device-card/device-card/device-card.tsx
  web/src/components/device-explorer/card-view/card-view.css
  web/src/components/device-explorer/device-explorer.css
  web/src/components/device-explorer/device-explorer.tsx
  web/src/components/header/header.css
  web/src/components/header/header.tsx
Labels: enhancement, bump:major

#710 UI update
  package-lock.json
  package.json
  src/public/asset-manifest.json
  src/public/index.html
  src/public/static/css/main.12a701ae.css
  src/public/static/css/main.12a701ae.css.map
  src/public/static/css/main.1f74dc45.css
  src/public/static/css/main.1f74dc45.css.map
  src/public/static/js/main.4862eae7.js
  src/public/static/js/main.4862eae7.js.LICENSE.txt
  src/public/static/js/main.4862eae7.js.map
  src/public/static/js/main.a331e350.js
  src/public/static/js/main.a331e350.js.LICENSE.txt
  src/public/static/js/main.a331e350.js.map
  src/public/static/media/android-nav-icon.4670118e9f775081ed597e634764f605.svg
  src/public/static/media/apple-icon.5112967f592a1aeff8323b26823c2bd8.svg
  src/public/static/media/apple-icon.a17e460ff848e58ea357b7d5e7dbb21f.svg
  src/public/static/media/apple-nav-icon.429cf1f0405cd5c622edbfb5835e22f8.svg
  src/public/static/media/apple-new-icon.568712db98ff3f83690a4e07bfe3d702.svg
  src/public/static/media/cancel-green-icon.71453b46237edaab5014a92125a3ed69.svg
  src/public/static/media/cancel-red-icon.52d51b858c8e96a30d4f9d79b52b92ea.svg
  src/public/static/media/device-farm-logo.90f2df7d84e57174f9c8.png
  src/public/static/media/link-icon.7336176ff32688423a9800543c6ee9f8.svg
  src/public/static/media/session-icon.de13b0401a71c8b2ee17117134dabd57.svg
  src/public/version.txt
  test/e2e/android/cloud/conf.spec.js
  test/e2e/android/cloud/confIOS.js
  test/e2e/android/conf2.spec.js
  test/e2e/android/conf3.spec.js
  web/src/App.css
  web/src/assets/android-nav-icon.svg
  web/src/assets/apple-icon.svg
  web/src/assets/apple-nav-icon.svg
  web/src/assets/cancel-green-icon.svg
  web/src/assets/cancel-red-icon.svg
  web/src/assets/device-farm-logo.png
  web/src/assets/link-icon.svg
  web/src/assets/session-icon.svg
  web/src/components/device-card/device-card/device-card.css
  web/src/components/device-card/device-card/device-card.tsx
  web/src/components/device-explorer/card-view/card-view.css
  web/src/components/device-explorer/device-explorer.css
  web/src/components/device-explorer/device-explorer.tsx
  web/src/components/header/header.css
  web/src/components/header/header.tsx
  web/yarn.lock
Labels: bug, bump:minor

#715 look for go-ios globally if local module fails
  package-lock.json
  package.json
  src/device-managers/iOSTracker.ts
Labels: bump:minor
